# Setup
title:               YORU
tagline:             'Your Optimal Recognition Utility'
description:         '“YORU” is an open-source sftware for animal behavior detection using an object detection. YORU classifies animal behavior as "behavior objects."' 
url:                 "https://kamikouchi-lab.github.io"
baseurl:             "/YORU_doc"
paginate:            5
permalink:           pretty
markdown:            kramdown

remote_theme: jekyll-theme-lanyon
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# About/contact
author:
  name:              Hayato M. Yamanouchi
  url:               https://github.com/HMYamano
  email:             haya.m.yamano.neuro@gmail.com


# Custom vars
version:             v 1.0.4
google_analytics_id: G-GT3X41B0YR


github:
  repo: https://github.com/Kamikouchi-lab/YORU
  user: HMYamano
  project: repository

Store:
  URL: https://www.zazzle.co.jp/store/yorustore?rf=238712148117349309
